version: "3"

services:
  postgres:
    image: postgres:10.11-alpine
    restart: on-failure
    ports:
      - 5432:5432
    #volumes:
    #  - "./.database:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres